version: '3.9'

services:
  web:
    build:
      context: ./geodjango
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    restart: always
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.4
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx    
    restart: always
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
  media_volume: